on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.10.4'
    - run: flutter packages get
    - run: flutter build apk --debug
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/*.apk"
        token: ${{ secrets.WORKFLOW_TOKEN }}
        commit: online-app
        tag: v1.0.${{ github.run_number }}
